### ISSUE TITLE
start-storybook crashes with:  identifier.indexOf is not a function

### ISSUE THREAD

**Issue by losh11** [storybookjs/react-native#19]
**Describe the bug**
Running `start-storybook` doesn't work. Instead the process crashes and gives the following error: 
```
/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:254
                const idxQuery = identifier.indexOf("?");
                                            ^

TypeError: identifier.indexOf is not a function
    at Resolver.parse (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:254:31)
    at resolver.getHook.tapAsync (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/ParsePlugin.js:16:28)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:34:13)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Resolver.doResolve (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at resolver.getHook.tapAsync (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/AliasFieldPlugin.js:43:13)
    at _next0 (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:638:1)
    at _fn0 (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:660:1)
    at resolver.getHook.tapAsync (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/AliasPlugin.js:53:11)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:652:1)
    at Resolver.doResolve (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/Resolver.js:235:16)
    at DescriptionFileUtils.loadDescriptionFile (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:38:14)
    at forEachBail (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:51:12)
    at args (/Users/loshan/Repos/{PROJECT_NAME_HERE}/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
```

**To Reproduce**
1. Create new react-native project.
2. `$ npx -p @storybook/cli sb init --type react_native`
3. `$ npm run storybook`

**Expected behavior**
Storybook should work.

**System:**
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v11.14.0/bin/yarn
    npm: 6.11.2 - ~/.nvm/versions/node/v11.14.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 66.0.5
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11 
    @storybook/addon-links: ^5.1.11 => 5.1.11 
    @storybook/addons: ^5.1.11 => 5.1.11 
    @storybook/react-native: ^5.1.11 => 5.1.11 
    @storybook/react-native-server: ^5.1.11 => 5.1.11 
  npmGlobalPackages:
    @storybook/cli: 5.1.11

**Additional context**
This is a duplicate of issue https://github.com/storybookjs/storybook/issues/5223. Unfortunately that issue received no replies and was auto closed by the bot due to inactivity.

**Comment by slavik0329** [comment]
Same issue here!

**Comment by ahmadaafaq** [comment]
same issue, has anyone found any working solution for this.

**Comment by markwindsorr** [comment]
same issue

**Comment by compojoom** [comment]
I'm thinking that something is missing in the docs. I added a simple console.log in the enhanced-resolve/lib/Resolver.js and the line with indexOf receives a function. 

I guess that we need some kind of config in babel.config to properly resolve the dependencies.

**Comment by compojoom** [comment]
Ok, just for the protocol. I did a clean RN installation and then installed storybook. Server starts fine. 

So it must be something in our project that is incompatible.

**Comment by singhvivek2503** [comment]
Same issue.

**Comment by alexander-akait** [comment]
Somebody can create reproducible test repo?

**Comment by jellyfish-tom** [comment]
still happening in 2021 :S

**Comment by georgewrmarshall** [comment]
I cross referenced our app with a fresh install of react native and storybook packages and it was because we didn't have `babel-loader` installed.

**Comment by dannyhw** [comment]
Any details about this issue? Or a reproduction?

**Comment by talon-i-am** [comment]
Ran into this today, had it working for a moment, then it broke again. Not sure what the cause is.

**Comment by dannyhw** [comment]
If someone can provide a repo with a reproduction or provide steps to reproduce that would help with debugging this.

**Comment by jellyfish-tom** [comment]
still happening

**Comment by dannyhw** [comment]
Still looking for a reproduction of this. If you have time please provide an example project with the broken behaviour and steps on how to reproduce.

**Comment by Einere** [comment]
I have same issue `undefined error ... indexOf`.
i found that some library like `react-native-localize`, `i18n-js`, `import {mergeAll, flatten} from 'ramda';` occurs error.
My Custom component use it. but after remove these library, storybook renders well.

**Comment by Markuson** [comment]
same here:
`TypeError: identifier.indexOf is not a function`

No solutions yet?

**Comment by dannyhw** [comment]
@Markuson 
any chance you can provide a public reproduction of this? Or could you provide the steps to reproduce?

**Comment by samandarkuchkarov** [comment]
same error

**Comment by dannyhw** [comment]
I would love to help with this but its not helpful when no-one is able to provide a reproduction. Please provide an example project with the problem easily reproducible so that I can more easily debug it. Its honestly getting pretty frustrating now how many times I already asked with no response...

**Comment by samandarkuchkarov** [comment]
Thank you, @dannyhw. I am successfully start storybook in clear project and after debugging my dependencies I find that 
dev dependence  rn-nodeify is main reason of error. If I add project this and run yarn storybook  error appeared
https://github.com/samandarkuchkarov/storybook-bug-example

**Comment by dannyhw** [comment]
@samandarkuchkarov Rn nodeify seems really problematic have you tried something like the solution offered here https://github.com/WalletConnect/walletconnect-monorepo/issues/753 ?

Nodeify modifies all of the packages in node modules which really isn't ideal and it's essentially a hack. I thinks its breaking something for enhanced resolve in webpack.
