### ISSUE TITLE
Errors and warning on a fresh startup

### ISSUE THREAD

**Issue by soullivaneuh** [storybookjs/react-native#198]
**Describe the bug**

After a fresh install of storybook on a fresh new expo typescript app, I have the following errors and warning app loading:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:617:3)
    at tryReadSync (node:fs:382:20)
    at Object.readFileSync (node:fs:419:19)
    at UnableToResolveError.buildCodeFrameMessage (/tmp/my-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/tmp/my-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/tmp/my-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/tmp/my-app/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /tmp/my-app/node_modules/metro/src/lib/transformHelpers.js:271:42
    at /tmp/my-app/node_modules/metro/src/Server.js:1097:37
    at Generator.next (<anonymous>)
Running application on ASUS_I01WD.
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:617:3)
    at tryReadSync (node:fs:382:20)
    at Object.readFileSync (node:fs:419:19)
    at UnableToResolveError.buildCodeFrameMessage (/tmp/my-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/tmp/my-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/tmp/my-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/tmp/my-app/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /tmp/my-app/node_modules/metro/src/lib/transformHelpers.js:271:42
    at /tmp/my-app/node_modules/metro/src/Server.js:1097:37
    at Generator.next (<anonymous>)

Starting Storybook v5.3.0, we require to manually pass an asyncStorage prop. Pass null to disable or use one from @react-native-community or react-native itself.
```

**To Reproduce**
1. Run `expo init -t expo-template-blank-typescript`
2. Go to the created project
3. Run `npx -p @storybook/cli sb init --type react_native`
4. Replace the default `App.tsx` code by the following: `export {default} from "./storybook";`
5. Run `expo start`
6. Use a phone to load the app.

**Expected behavior**

A working basic react-native storybook without any error on the console 

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

Despite of those errors, the app is loading. However, on an another project managing multiple stories, the `EISDIR` error happens a lot of time.

**Comment by dannyhw** [comment]
Please can you provide information about your system
> paste the results of npx -p @storybook/cli@next sb info here.

**Comment by Einere** [comment]
i have same error.
```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:564:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/lib/transformHelpers.js:271:42
    at Server.<anonymous> (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/Server.js:842:41)
    at Generator.next (<anonymous>)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:564:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/lib/transformHelpers.js:271:42
    at Server.<anonymous> (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/Server.js:842:41)
    at Generator.next (<anonymous>)
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:564:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at UnableToResolveError.buildCodeFrameMessage (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at /Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/lib/transformHelpers.js:271:42
    at Server.<anonymous> (/Users/einere/WebstormProjects/light-mobile-app/node_modules/metro/src/Server.js:842:41)
    at Generator.next (<anonymous>)
```

and system info is below.
```
Environment Info:

  System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 87.0
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-actions: ^5.3 => 5.3.21 
    @storybook/addon-knobs: ^5.3 => 5.3.21 
    @storybook/addon-links: ^5.3 => 5.3.21 
    @storybook/addon-ondevice-actions: ^5.3.23 => 5.3.23 
    @storybook/addon-ondevice-knobs: ^5.3.25 => 5.3.25 
    @storybook/react-native: ^5.3.25 => 5.3.25 
    @storybook/react-native-server: ^5.3.23 => 5.3.23 
```

**Comment by dannyhw** [comment]
Could you provide a public repository that reproduces this problem?

**Comment by Einere** [comment]
@dannyhw 
New project made by `react-native init` with storybook is working well..
But, sorry for that the project is private repository.. 😅  so, it's hard to share the project repository.

**Comment by Einere** [comment]
@dannyhw 
My private project using "react-native-splash-screen" package.
When run debug mode (android), splash screen is not hiding.
So, i fixed `MainActivity.java` code to not showing splash screen.

```java
public class MainActivity extends ReactActivity {
    ReactContext reactContext;
    PopupWindow popupWindow;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
//         SplashScreen.show(this, R.style.SplashScreenTheme); // I commented this line to not showing splash screen
        super.onCreate(null);
        this.setVolumeControlStream(AudioManager.STREAM_MUSIC);
```
and rollback all changes (git), reinstall storybook by `npx -p @storybook/cli sb init`.
Then storybook show in device. but still exist some issues.
- ~not showing appropriate preview when touch Button story in device. (only show Welcome preview)~ storybook show appropriate preview when i fix story codes.
- ~storybook server not connected with device. so left pane not show stories in browser.~ i resolve this issue by #55
- ~`EISDIR` error is logged too.~
