### ISSUE TITLE
Expo start error on pnpm monorepo

### ISSUE THREAD

**Issue by tcolinpa** [storybookjs/react-native#400]
**Describe the bug**
I've tried to use [this template](https://github.com/dannyhw/expo-template-storybook) inside a pnpm monorepo with nested workspaces, however it runs into an random error when I run `expo start` that I have no idea where to begin:

```
Starting Metro Bundler
Failed to construct transformer:  Error: jest-haste-map: File to process was not found in the haste map.
    at HasteMap._processFile (/Users/tiagocolin/Projects/quaddro/node_modules/metro/node_modules/jest-haste-map/build/index.js:628:13)
    at HasteMap._buildHasteMap (/Users/tiagocolin/Projects/quaddro/node_modules/metro/node_modules/jest-haste-map/build/index.js:809:28)
    at /Users/tiagocolin/Projects/quaddro/node_modules/metro/node_modules/jest-haste-map/build/index.js:459:33
    at async DependencyGraph.load (/Users/tiagocolin/Projects/quaddro/node_modules/metro/src/node-haste/DependencyGraph.js:86:36)
    at async Bundler.ready (/Users/tiagocolin/Projects/quaddro/node_modules/metro/src/Bundler.js:61:5)
    at async IncrementalBundler.ready (/Users/tiagocolin/Projects/quaddro/node_modules/metro/src/IncrementalBundler.js:309:5)
    at async Server.ready (/Users/tiagocolin/Projects/quaddro/node_modules/metro/src/Server.js:1187:5)
  ```

**Expected behavior**
Open expo app on simulator

**Code snippets**
ui/mobile/package.json
```
  "main": "index.ts",
  "dependencies": {
    "expo": "^46.0.0",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@storybook/addon-actions": "~6.3",
    "@storybook/addon-controls": "~6.3",
    "@storybook/addon-essentials": "~6.3",
    "@storybook/addon-links": "~6.3",
    "@storybook/addon-ondevice-actions": "next",
    "@storybook/addon-ondevice-backgrounds": "next",
    "@storybook/addon-ondevice-controls": "next",
    "@storybook/addon-ondevice-notes": "next",
    "@storybook/addon-react-native-web": "^0.0.19",
    "@storybook/react": "~6.3",
    "@storybook/react-native": "5.3.25",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "babel-loader": "^8.2.3",
    "babel-plugin-react-native-web": "~0.18.7",
    "typescript": "^4.6.3"
  }
  ```
  metro.config.js
  ```
  const { getDefaultConfig } = require('expo/metro-config')

const defaultConfig = getDefaultConfig(__dirname)

defaultConfig.resolver.resolverMainFields = [
  'sbmodern',
  ...defaultConfig.resolver.resolverMainFields
]

defaultConfig.transformer.getTransformOptions = async () => ({
  transform: {
    experimentalImportSupport: false,
    inlineRequires: false
  }
})

defaultConfig.watchFolders = [...defaultConfig.watchFolders, './.ondevice', `${__dirname}/../..`]

module.exports = defaultConfig
```

**System:**
```
Environment Info:

  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 15.1
```

**Additional context**
I'm using a pnpm monorepo with the following folder structure and each folder has its own package.json
```
packages
     /ui --> runs storybook composition
         /core --> design system tokens, just a bunch of objects
         /web --> storybook react + vite
         /mobile --> storybook expo
```

Everything else such as .ondevice and .storybook is exactly the same as the template.

**Comment by dannyhw** [comment]
@tcolinpa I think react native has issues in general with pnpm, do your apps normally work with pnpm?

**Comment by tcolinpa** [comment]
@dannyhw thanks for the fast response.

yeah, we actually have another package in the same workspace with expo running `apps/mobile`, runs without errors

**Comment by dannyhw** [comment]
Do you have any extra config for that to work?

**Comment by dannyhw** [comment]
also can you try updating to "^6.5" for those storybook dependencies that are currently on "~6.3" and use the latest beta [6.0.1-beta.10](https://github.com/storybookjs/react-native/releases/tag/v6.0.1-beta.10)

**Comment by dannyhw** [comment]
Pnpm issues are more related to react native than storybook. Let me know if i should reopen though.
