### ISSUE TITLE
TypeError: Invalid Version: null

### ISSUE THREAD

**Issue by dancomanlive** [storybookjs/react-native#464]
**Describe the bug**

```
 • Installing Storybook for user specified project type: react_native. ✓
TypeError: Invalid Version: null
    at new SemVer (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/semver/classes/semver.js:19:13)
    at compare (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/semver/functions/compare.js:3:3)
    at Object.gte (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/semver/functions/gte.js:2:30)
    at /Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:13:6403
    at hasDependency (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:13:3968)
    at detectLanguage (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:13:6332)
    at installStorybook (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:322:1936)
    at doInitiate (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:352:131)
    at async withTelemetry (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/core-server/dist/index.js:35:3422)
    at async initiate (/Users/user/.npm/_npx/eebb2d3a7d26a7f1/node_modules/@storybook/cli/dist/generate.js:363:109)
```

**To Reproduce**
`npx sb@next init --type react_native`

**Expected behavior**
I expect to not get an error.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

`Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M2 Pro
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 111.0.1
    Safari: 16.3`

**Additional context**

Using react native app(0.70.6) (*not EXPO* ). The mobile project is included inside a monorepo. When installing `npx sb@next init --type react_native` one level up it works.

**Comment by dancomanlive** [comment]
Solution: 

`1. npx -p @storybook/cli sb init --type react_native`
`2. npx sb@next init --type react_native`

**Comment by dannyhw** [comment]
this seems like a related issue https://github.com/storybookjs/storybook/issues/21806, are you using typescript?

**Comment by dancomanlive** [comment]
@dannyhw Thanks for the quick reply. Yes, I am using Typescript 5.0.4.

**Comment by dannyhw** [comment]
can you try it with 4.9 temporarily to see if it gets past the error?

**Comment by dancomanlive** [comment]
I confirm it's working with 4.8.4, which is the version installed when using `npx react-native init MyApp --template react-native-template-storybook`.

**Comment by dannyhw** [comment]
ok well it seems like the team is working on a fix so for now I suggest to run the command with that version and then revert typescript to the 5.0.4 once its generated the project.
