### ISSUE TITLE
Unable to resolve module ./storybook.requires

### ISSUE THREAD

**Issue by Brandon-Perry** [storybookjs/react-native#473]
**Describe the bug**
When I yarn start on my project after installing storybook, I get the following error:

error: Error: Unable to resolve module ./storybook.requires from /Users/brandon/Desktop/monorepo/client/.storybook/index.js: 

None of these files exist:
  * .storybook/storybook.requires(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * .storybook/storybook.requires/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  1 | import { getStorybookUI } from '@storybook/react-native';
  2 |
> 3 | import './storybook.requires';
    |         ^
  4 |
  5 | const StorybookUIRoot = getStorybookUI({});
  6 |
    at ModuleResolver.resolveDependency (/Users/brandon/Desktop/monorepo/client/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:137:15)
    at DependencyGraph.resolveDependency (/Users/brandon/Desktop/monorepo/client/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/brandon/Desktop/monorepo/client/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/brandon/Desktop/monorepo/client/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/brandon/Desktop/monorepo/client/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/Users/brandon/Desktop/monorepo/client/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 5)
    at async Graph._processModule (/Users/brandon/Desktop/monorepo/client/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._traverseDependenciesForSingleFile (/Users/brandon/Desktop/monorepo/client/node_modules/metro/src/DeltaBundler/Graph.js:207:5)
    at async Promise.all (index 0)

**To Reproduce**
1. install storybook in client with `npx sb@next init --type react_native`
2. Add the following line to metro.config.js `resolver: {
    resolverMainFields: ['sbmodern', 'react-native', 'browser', 'main']
  }` 
3. Add `export {default} from './.storybook'` to app entrypoint
4. yarn start

**Expected behavior**
I expect metro to run without failure

**System:**
Environment Info:

  System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.63
    Firefox: 112.0.1
    Safari: 16.3
  npmPackages:
    @storybook/addon-actions: ^6.5.16 => 6.5.16 
    @storybook/addon-controls: ^6.5.16 => 6.5.16 
    @storybook/addon-ondevice-actions: ^6.5.3 => 6.5.3 
    @storybook/addon-ondevice-controls: ^6.5.3 => 6.5.3 
    @storybook/cli: ^7.0.9 => 7.0.9 
    @storybook/react-native: ^6.5.3 => 6.5.3 

**Additional context**
Running Yarn storybook also does not result in anything happening, the storyboard docs say that it should have started it up.

**Comment by dannyhw** [comment]
this file is generated you need to run the script which would be something like
```
    "update-stories": "sb-rn-get-stories",

**Comment by DrBlackBird** [comment]
I have the same problem. Just tried to add Storybook to my expo project but I receive the same error as @Brandon-Perry 

@dannyhw  how do I execute the command? 

ah sorry. `yarn storybook-generate` fixes the error which is already present in the package.json. Sorry! :)

**Comment by dannyhw** [comment]
The a default requires file will be added to the template to hopefully reduce the frequency of this. Leaving open until I make that change.
