### ISSUE TITLE
Issues starting a new project from scratch

### ISSUE THREAD

**Issue by samducker** [storybookjs/react-native#656]
**Describe the bug**
I installed the new project template with expo then read the readme and made sure my metro and babel was correct, and I encounter the following issue on startup. 

I go to run yarn ios (I've also tried prebuild clean, and adding no build cache to yarn ios)

```
Metro has encountered an error:
context.fileSystemLookup is not a function: /Users/mac/Documents/GitHub/project/app/packages/mobile-ui/node_modules/metro-resolver/src/resolve.js (449:32)

447 |        };
448 |    }
> 449 |    const lookupResult = context.fileSystemLookup(redirectedPath);
450 |    if (lookupResult.exists && lookupResult.type === "f") {
451 |        return lookupResult.realPath;
452 |    }

RCTFatal

__28-[RCTCxxBridge handleError:]_block_invoke

_dispatch_call_block_and_release

_dispatch_client_callout

_dispatch_main_queue_drain

_dispatch_main_queue_callback_4CF

__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__

__CFRunLoopRun
```

**To Reproduce**
Install the template with expo from scratch on the latest version

**Additional context**
I'm in a monorepo setup with yarn workspaces, my project has another expo app in a different project within the monorepo

**Comment by dannyhw** [comment]
@samducker  Can you provide the exact commands that you ran to create the project?

**Comment by dannyhw** [comment]
since theres been no activity I will close this for now, let me know if you want to reopen

**Comment by omerman** [comment]
Getting this too.
@dannyhw 
ran: `yarn create tamagui@latest --template expo-router`

**Comment by tlow92** [comment]
@dannyhw Faced same issue on current starter.
1. `npm create tamagui@latest --template expo-router`
2. --template does not seem to work so select `expo router (beta)` manually
3. `cd expo-router`
4. `npx expo export -p web && npx serve dist --single`

Leads to:

```bash
Starting Metro Bundler
Static rendering is enabled. Learn more

  ➡ [tamagui] built config and components (714ms)
  ➡ [tamagui] output css: ./tamagui-web.css
TypeError: context.fileSystemLookup is not a function
TypeError: context.fileSystemLookup is not a function
    at resolveSourceFileForExt (/Users/thiloreiner/Documents/git/expo-router/node_modules/metro-resolver/src/resolve.js:449:32)
    at resolveSourceFileForAllExts (/Users/thiloreiner/Documents/git/expo-router/node_modules/metro-resolver/src/resolve.js:435:20)
    at resolveSourceFile (/Users/thiloreiner/Documents/git/expo-router/node_modules/metro-resolver/src/resolve.js:407:18)
    at resolveFile (/Users/thiloreiner/Documents/git/expo-router/node_modules/metro-resolver/src/resolve.js:390:32)
    at resolveModulePath (/Users/thiloreiner/Documents/git/expo-router/node_modules/metro-resolver/src/resolve.js:224:7)
    at resolver (/Users/thiloreiner/Documents/git/expo-router/node_modules/metro-resolver/src/resolve.js:45:20)
    at doResolve (/Users/thiloreiner/Documents/git/expo-router/node_modules/@expo/cli/src/start/server/metro/withMetroMultiPlatform.ts:242:14)
    at resolver (/Users/thiloreiner/Documents/git/expo-router/node_modules/@expo/cli/src/start/server/metro/withMetroMultiPlatform.ts:382:22)
    at firstResolver (/Users/thiloreiner/Documents/git/expo-router/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:76:29)
    at resolveRequest (/Users/thiloreiner/Documents/git/expo-router/node_modules/@expo/cli/src/start/server/metro/withMetroResolvers.ts:108:16)
```

**Comment by dannyhw** [comment]
Hey @tlow92, not sure because that sounds a lot like an issue with the expo router template, I'm not sure I understand how it relates to storybook in this case. Can you elaborate or create a new issue?

**Comment by tlow92** [comment]
Sorry, nevermind my mistake. I mixed up in which repository the issue lives in, you are right!

**Comment by dannyhw** [comment]
no problem :)
